# HOMEWORK

### Q1. Pandas version

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.3'

#### Answer = 2.2.3

### Q2. Records count

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-22 22:11:32--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv.5’

laptops.csv.5       100%[===================>] 291.58K  --.-KB/s    in 0.09s   

2024-09-22 22:11:32 (3.20 MB/s) - ‘laptops.csv.5’ saved [298573/298573]



In [3]:
!ls

laptops.csv    laptops.csv.2  laptops.csv.4  mlz-01.ipynb
laptops.csv.1  laptops.csv.3  laptops.csv.5  venv


In [4]:
df = pd.read_csv('./laptops.csv')

In [5]:
df.describe

<bound method NDFrame.describe of                                                  Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

     

#### Answer = 2160

### Q3. Laptop brands

In [6]:
df[['Brand']].nunique()

Brand    27
dtype: int64

#### Answer = 27

### Q4. Missing values

In [7]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

#### Answer = 2

### Q5. Maximum final price

In [8]:
df[df['Brand'] == 'Dell'][['Final Price']].max()

Final Price    3936.0
dtype: float64

#### Answer = 3936.0

### Q6. Median value of Screen

In [9]:
df[['Screen']].median()

Screen    15.6
dtype: float64

In [10]:
screen_mode=df[['Screen']].mode()['Screen'][0]
print(screen_mode)

15.6


In [11]:
df[['Screen']] = df[['Screen']].fillna(value=screen_mode)

In [12]:
df[['Screen']].median()

Screen    15.6
dtype: float64

#### Answer = No

### Q7. Sum of weights

In [13]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [14]:
X = df[df['Brand']=='Innjoo'][['RAM', 'Storage', 'Screen']].to_numpy()

In [15]:
X_T = X.transpose()
print(X)
print(X_T)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]
[[  8.    8.    4.    6.    6.    6. ]
 [256.  512.   64.   64.  128.  128. ]
 [ 15.6  15.6  14.1  14.1  14.1  14.1]]


In [16]:
XTX = np.matmul(X_T, X)

In [17]:
iXTX = np.linalg.inv(XTX)

In [18]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [19]:
w = np.matmul(np.matmul(iXTX, X_T), y)

In [20]:
w.sum()

np.float64(91.29988062995588)

#### Answer = 91.30